name: Test

on: [push, pull_request]         # triggers on

jobs:
  build:
    runs-on: ubuntu-latest       # runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # uses a GHA from https://github.com/marketplace?type=actions
    - name: Hello World!
      run: echo "Hello World!"   # runs the script
